name: CI Pipeline (GitOps)

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-update-gitops:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Application Code
        uses: actions/checkout@v3

      - name: Set Image Tag
        id: vars
        run: echo "tag=${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/secure-task-manager:${{ steps.vars.outputs.tag }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/secure-task-manager:${{ steps.vars.outputs.tag }}

      - name: Clone GitOps Repository
        run: |
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/ezio7223//secure-task-manager-gitops.git

      - name: Update Deployment YAML Image Tag
        run: |
          cd secure-task-manager-gitops
          sed -i "s|image:.*|image: ${{ secrets.DOCKER_USERNAME }}/secure-task-manager:${{ steps.vars.outputs.tag }}|" GitOps/K8/deployment.yaml
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update image to ${{ steps.vars.outputs.tag }}"
          git push