name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Image Tag
          run: echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/secure-task-manager:${IMAGE_TAG} .

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/secure-task-manager:${IMAGE_TAG}

      - name: Deploy to Kubernetes
          run: |
            kubectl set image deployment/secure-task-manager \
            secure-task-manager=ezio7223/secure-task-manager:${IMAGE_TAG}

      - name: Verify Rollout
          run: kubectl rollout status deployment secure-task-manager