name: CI Pipeline (GitOps)

on:
  push:
    branches:
      - main

jobs:
  build-and-update-gitops:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Application Code
        uses: actions/checkout@v3

      - name: Set Short SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/secure-task-manager:${{ steps.vars.outputs.sha_short }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/secure-task-manager:${{ steps.vars.outputs.sha_short }}

      - name: Update GitOps Repository
        run: |
          # 1. Clone the SECOND repository using the PAT
          git clone https://x-access-token:${{ secrets.GITOPS_PAT }}@github.com/ezio7223/secure-task-manager-gitops.git
          cd secure-task-manager-gitops
          
          # 2. Update the image tag in the GitOps repo
          # Note: Adjust the path if your deployment.yaml is in a different subfolder
          sed -i "s|image:.*|image: ${{ secrets.DOCKER_USERNAME }}/secure-task-manager:${{ steps.vars.outputs.sha_short }}|" GitOps/K8/deployment.yaml
          
          # 3. Push the change back to the GitOps repo
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update image to ${{ steps.vars.outputs.sha_short }}"
          git push